---
- name: MY AS3 PLAYBOOK
  hosts: localhost
  connection: local 
  gather_facts: false

  vars:
    URI_METHOD: "POST"

  vars_files:
    - ../creds/big_creds.yml

  tasks:
    - name: Create AS3 Decleration
      uri:
        url: https://{{ BIG_IP }}/mgmt/shared/appsvcs/declare/
        user: "{{ BIG_USER }}"
        password: "{{ BIG_PASS }}"
        validate_certs: false
        method: "{{ URI_METHOD }}"
        body: "{{ lookup('file','as3-declaration.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
      register: as3_response

    - name: AS3 RESPONSE OUTPUT
      debug:
        msg: "{{ as3_response }}"